delegate:
  subAppId: rdm_83f47cac09064530837465ac4dd55c20_app
  domain: https://dme.cn-north-4.huaweicloud.com
  domainName: jomocool
  userName: pan1131240003
  password: abc123
  endpoint: https://iam.cn-north-4.myhuaweicloud.com
  regionName: cn-north-4
  serviceType: services/dynamic


server:
  port: 8080
